// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/string-length": {
    params: {};
  };
  "/generate-uuid-v4": {
    params: {};
  };
  "/video-to-gif": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/string-length" | "/generate-uuid-v4" | "/video-to-gif";
  };
  "layout/layout.tsx": {
    id: "layout/layout";
    page: "/" | "/string-length" | "/generate-uuid-v4" | "/video-to-gif";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "layout/tool-layout.tsx": {
    id: "layout/tool-layout";
    page: "/string-length" | "/generate-uuid-v4" | "/video-to-gif";
  };
  "tools/StringLengthTool.tsx": {
    id: "tools/StringLengthTool";
    page: "/string-length";
  };
  "tools/RandomUUIDv4Tool.tsx": {
    id: "tools/RandomUUIDv4Tool";
    page: "/generate-uuid-v4";
  };
  "tools/VideoToGif.tsx": {
    id: "tools/VideoToGif";
    page: "/video-to-gif";
  };
};